version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: todo-solestone
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth_service
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      DATABASE_URL: postgresql://postgres:admin@postgres:5432/todo-solestone
    depends_on:
      - postgres


volumes:
  postgres_data:
